### ISSUE TITLE
error while trying to split the database

### ISSUE THREAD

**Issue by saniya052** [abhay8463/Speech-Emotion-Recognition-using-ML-and-DL#1]
ValueError: With n_samples=0, test_size=0.25 and train_size=0.75, the resulting train set will be empty. Adjust any of the aforementioned parameters.

**Comment by Apurva934** [comment]
> ValueError: With n_samples=0, test_size=0.25 and train_size=0.75, the resulting train set will be empty. Adjust any of the aforementioned parameters.

Its because the google drive path is incorrect. Make sure you have all files copied in a single folder.
